// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDafugHcApk9g_LslFTOVF8X5KXjjqNR0I',
    appId: '1:905773810513:web:4dc57698b9ef2f24380970',
    messagingSenderId: '905773810513',
    projectId: 'inventory-app-5560d',
    authDomain: 'inventory-app-5560d.firebaseapp.com',
    storageBucket: 'inventory-app-5560d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjBsYAqerx1lBVYcL9s4OLGT2mQg_h1Jo',
    appId: '1:905773810513:android:fbd8630aa7f92547380970',
    messagingSenderId: '905773810513',
    projectId: 'inventory-app-5560d',
    storageBucket: 'inventory-app-5560d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbadKTf8UtDYAEpV6IgzbVRHJkIUgcxA',
    appId: '1:905773810513:ios:8c9cca3edfd3449a380970',
    messagingSenderId: '905773810513',
    projectId: 'inventory-app-5560d',
    storageBucket: 'inventory-app-5560d.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbadKTf8UtDYAEpV6IgzbVRHJkIUgcxA',
    appId: '1:905773810513:ios:8c9cca3edfd3449a380970',
    messagingSenderId: '905773810513',
    projectId: 'inventory-app-5560d',
    storageBucket: 'inventory-app-5560d.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDafugHcApk9g_LslFTOVF8X5KXjjqNR0I',
    appId: '1:905773810513:web:aac71f5b68a8a1eb380970',
    messagingSenderId: '905773810513',
    projectId: 'inventory-app-5560d',
    authDomain: 'inventory-app-5560d.firebaseapp.com',
    storageBucket: 'inventory-app-5560d.firebasestorage.app',
  );
}
